type coq_P4String = Info.t Poulet4.Syntax.coq_P4String
type coq_P4Int = Info.t Poulet4.Syntax.coq_P4Int
type coq_MethodPrototype = Info.t Poulet4.Syntax.coq_MethodPrototype
type coq_OpUni = Poulet4.Syntax.coq_OpUni
type coq_OpBin = Poulet4.Syntax.coq_OpBin
type coq_KeyValue = Info.t Poulet4.Syntax.coq_KeyValue
and coq_ExpressionPreT = Info.t Poulet4.Syntax.coq_ExpressionPreT
and coq_Expression = Info.t Poulet4.Syntax.coq_Expression
type coq_MatchPreT = Info.t Poulet4.Syntax.coq_MatchPreT
type coq_Match = Info.t Poulet4.Syntax.coq_Match
type coq_TablePreActionRef = Info.t Poulet4.Syntax.coq_TablePreActionRef
type coq_TableActionRef = Info.t Poulet4.Syntax.coq_TableActionRef
type coq_TableKey = Info.t Poulet4.Syntax.coq_TableKey
type coq_TableEntry = Info.t Poulet4.Syntax.coq_TableEntry
type coq_TableProperty = Info.t Poulet4.Syntax.coq_TableProperty
type coq_ValueBase = Info.t Poulet4.Syntax.coq_ValueBase
and coq_ValueSet = Info.t Poulet4.Syntax.coq_ValueSet
type coq_StatementSwitchLabel = Info.t Poulet4.Syntax.coq_StatementSwitchLabel
type coq_StatementSwitchCase = Info.t Poulet4.Syntax.coq_StatementSwitchCase
and coq_StatementPreT = Info.t Poulet4.Syntax.coq_StatementPreT
and coq_Statement = Info.t Poulet4.Syntax.coq_Statement
and coq_Block = Info.t Poulet4.Syntax.coq_Block
type coq_ParserCase = Info.t Poulet4.Syntax.coq_ParserCase
type coq_ParserTransition = Info.t Poulet4.Syntax.coq_ParserTransition
type coq_ParserState = Info.t Poulet4.Syntax.coq_ParserState
type coq_DeclarationField = Info.t Poulet4.Syntax.coq_DeclarationField
type coq_Declaration = Info.t Poulet4.Syntax.coq_Declaration
type coq_ValueTable = Info.t Poulet4.Syntax.coq_ValueTable
type coq_Env_EvalEnv = Poulet4.Syntax.coq_Env_EvalEnv
type coq_ValuePreLvalue = Info.t Poulet4.Syntax.coq_ValuePreLvalue
and coq_ValueLvalue = Info.t Poulet4.Syntax.coq_ValueLvalue
type coq_ValueObject = Info.t Poulet4.Syntax.coq_ValueObject
type coq_ValueConstructor = Info.t Poulet4.Syntax.coq_ValueConstructor
type coq_Value = Info.t Poulet4.Syntax.coq_Value
type program = Info.t Poulet4.Syntax.program
